name: Deploy to GitHub Pages

on:
  push:

jobs:
  build_android:
    runs-on: ubuntu-22.04
    container:
      image: ivangabriele/tauri:debian-bullseye-18
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install packages
      run: |
        apt install -y \
          build-essential \
          curl \
          wget \
          file \
          libxdo-dev \
          libssl-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Setup Android SDK 2
      run: sdkmanager --install "ndk;27.2.12479018"
    - name: Install Tauri
      run: |
        cargo install tauri-cli
        rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
    - name: Build APK
      run: |
        npm install
        export NDK_HOME="$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)"
        cargo tauri android build
    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'src-tauri/gen/android/app/build/outputs/apk/universal/release/'

  build_site:
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: build
        run: npm run build
      - name: Debug build output
        run: |
          echo "Build directory contents:"
          ls -la build/
          echo "\nRecursive build directory structure:"
            find build/ -type f
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
