name: Deploy to GitHub Pages

on:
  push:

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: build
        run: |
          npm run build
          cp build/index.html build/404.html
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
          name: 'github-pages'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: 'github-pages'
          path: 'artifacts/github-pages/'
      - name: Display structure of downloaded files
        run: |
          ls -R artifacts
          tar -xvf artifacts/github-pages/artifact.tar
          ls -R artifacts
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: 'github-pages'

